### PR TITLE
Adding 8SQRD to CCSPA Registry

### PR DESCRIPTION
**Pull request by jhuynh64**

### CODE REVIEW

**Comment by jhuynh64** [comment]
Hey @codefly -- I recently just found out that we never added ourselves (8SQRD) to this registry.

Could you please take a look at this pull request? Thanks!

**Review by codefly — APPROVED** [review]
looks good!

**Comment by jhuynh64** [comment]
Thanks @codefly -- I don't have write access, could you please merge this in for us?

**Comment by codefly** [comment]
Sorry, thought it did!

**Pull request merged**
